forums/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ForumList.as_view(), name='forums_home'),
    path('<int:pk>/', views.ForumDetail.as_view(), name='forums_detail'),
    path('<int:forum_id>/threads/', views.ThreadCreate.as_view(), name='threads_create'),
    path('threads/<int:pk>/', views.ThreadDetail.as_view(), name='threads_detail'),
    path('threads/<int:pk>/delete', views.ThreadDelete.as_view(), name='threads_delete'),
    path('threads/<int:thread_id>/posts', views.PostCreate.as_view(), name='posts_create'),
    path('threads/<int:thread_id>/posts/<int:post_id>/reply', views.PostReply.as_view(), name='posts_reply'),
    path('posts/<int:pk>/delete', views.PostDelete.as_view(), name='posts_delete'),
    path('posts/<int:pk>/edit', views.PostEdit.as_view(), name='posts_edit'),
]

walkr/urls.py
import os

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views
from django.conf import settings

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('walks/', include('walks.urls')),
    path('forums/', include('forums.urls')),
]

if os.getenv('DEV'):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forums/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()
COMMENTS_FORUM_NAME = "Walk Comments"
COMMENTS_FORUM_DESCRIPTION = "A special forum to comment on walks."


def get_comments_forum():
    forum, created = Forum.objects.get_or_create(
        title=COMMENTS_FORUM_NAME,
        defaults={'description': COMMENTS_FORUM_DESCRIPTION},
    )
    return forum


class Forum(models.Model):
    title = models.CharField(max_length=64)
    description = models.TextField()

    def __str__(self):
        return self.title


class Thread(models.Model):
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=64)
    created = models.DateTimeField(auto_now_add=True)
    post_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class Post(models.Model):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    reply_to = models.ForeignKey('self', null=True, on_delete=models.SET_NULL)
    position = models.PositiveIntegerField()
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Post {self.position} in Thread: {self.thread}"

forums/forms.py
from django.forms import ModelForm

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text']

forums/views.py
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin

from .models import Forum, Thread, Post
from .forms import PostForm


class ForumList(ListView):
    model = Forum


class ForumDetail(DetailView):
    model = Forum


class ThreadDetail(DetailView):
    model = Thread

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_form'] = PostForm()
        return context


class ThreadCreate(LoginRequiredMixin, CreateView):
    model = Thread
    fields = ['title']

    def form_valid(self, form):
        form.instance.forum_id = self.kwargs['forum_id']
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['forum'] = Forum.objects.get(id=self.kwargs['forum_id'])
        return context

    def get_success_url(self):
        return reverse('threads_detail', kwargs={ 'pk': self.object.id })


class ThreadDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Thread

    def test_func(self):
        return self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse('forums_detail', kwargs={ 'pk': self.object.forum.id })


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['text']

    def form_valid(self, form):
        thread = Thread.objects.get(id=self.kwargs['thread_id'])
        thread.post_count = thread.post_count + 1
        thread.save()

        form.instance.author = self.request.user
        form.instance.position = thread.post_count
        form.instance.thread_id = self.kwargs['thread_id']

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['thread'] = Thread.objects.get(id=self.kwargs['thread_id'])
        return context

    def get_success_url(self):
        return reverse('threads_detail', kwargs={ 'pk': self.kwargs['thread_id'] })


class PostReply(PostCreate):
    def form_valid(self, form):
        form.instance.reply_to = Post.objects.get(id=self.kwargs['post_id'])
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reply_to'] = Post.objects.get(id=self.kwargs['post_id'])
        return context


class PostEdit(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['text']

    def test_func(self):
        return self.get_object().author == self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['thread'] = self.object.thread
        return context

    def get_success_url(self):
        return reverse('threads_detail', kwargs={ 'pk': self.object.thread.id })


class PostDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post

    def test_func(self):
        return self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse('threads_detail', kwargs={ 'pk': self.object.thread.id })

forums/templates/forums/forum_detail.html
{% extends 'base.html' %}
{% block title %}
{{ forum.title }}
{% endblock %}
{% block content %}

<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'forums_home' %}">Forums</a></li>
    <li class="breadcrumb-item active">{{ forum.title }}</li>
  </ol>
</nav>

<h1>{{ forum.title }}</h1>
<p>{{ forum.description }}</p>

<a class="btn btn-primary" href="{% url 'threads_create' forum.id %}">New Thread</a>
<hr>

<h2>Threads</h2>
<div class="list-group">
{% for thread in forum.thread_set.all %}
  <a class="list-group-item list-group-item-action"  href="{% url 'threads_detail' thread.id %}">
    <span class="text-primary">{{ thread.title }}</span>
    <br>
    <small>created by <b>{{ thread.author.username }}</b> on {{ thread.created }}</small>
  </a>
{% empty %}
  Nothing here...
{% endfor %}
</div>

{% endblock %}

forums/templates/forums/forum_list.html
{% extends 'base.html' %}
{% block title %}
Forums
{% endblock %}
{% block content %}

<h1>Forums</h1>

<hr>

<div class="list-group">
{% for forum in forum_list %}
  <a class="list-group-item list-group-item-action" href="{% url 'forums_detail' forum.id %}">
    <span class="h5 text-primary">{{ forum.title }}</span>
    <br>
    <small>{{ forum.description }}</small>
  </a>
{% endfor %}
</div>

{% endblock %}

forums/templates/forums/post_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
Delete Post
{% endblock %}
{% block content %}

{% load bootstrap4 %}

<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url 'forums_home' %}">Forums</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{% url 'forums_detail' post.thread.forum.id %}">{{ post.thread.forum.title }}</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{% url 'threads_detail' post.thread.id %}">{{ post.thread.title }}</a>
    </li>
    <li class="breadcrumb-item active">
      Delete Post #{{ post.position }} 
    </li>
  </ol>
</nav>

<h1>Delete Post</h1>
<form action="" method="post">
  {% csrf_token %}
  Thread: <b>{{ post.thread.title }}</b>, You said:
  <div class="card">
    <div class="card-body">
      {{ post.text }}
    </div>
  </div>
  <br>
  <input class="btn btn-danger" type="submit" value="DELETE">
  <a href="{% url 'threads_detail' post.thread.id %}">Go back</a>
</form>

{% endblock %}

forums/templates/forums/post_form.html
{% extends 'base.html' %}
{% block title %}
Post
{% endblock %}
{% block content %}

{% load bootstrap4 %}

<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url 'forums_home' %}">Forums</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{% url 'forums_detail' thread.forum.id %}">{{ thread.forum.title }}</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{% url 'threads_detail' thread.id %}">{{ thread.title }}</a>
    </li>
    <li class="breadcrumb-item">
      New Post
    </li>
  </ol>
</nav>

<h1>Post</h1>

{% if reply_to %}
In reply to #{{ reply_to.position }} by <b>{{ reply_to.author }}</b> in <b>{{ thread.title }}</b>
<div class="card my-2">
  <div class="card-body">
    {{ reply_to.text }}
  </div>
</div>
You say:
{% else %}
Posting to <b>{{ thread.title }}</b>:
{% endif %}

<form action="" method="post">
  {% csrf_token %}
  {% bootstrap_form_errors form %}
  {% bootstrap_field form.text show_label=False %}
  <button class="btn btn-primary" type="submit">Post</button>
</form>

{% endblock %}

forums/templates/forums/thread_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
Delete Thread
{% endblock %}
{% block content %}

{% load bootstrap4 %}

<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url 'forums_home' %}">Forums</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{% url 'forums_detail' thread.forum.id %}">{{ thread.forum.title }}</a>
    </li>
    <li class="breadcrumb-item active">
      Delete Thread {{ thread.title }} 
    </li>
  </ol>
</nav>

<h1>Delete Thread</h1>
<form action="" method="post">
  {% csrf_token %}
  Are you sure you want to delete thread: <b>{{ thread.title }}</b>
  <br>
  <br>
  <input class="btn btn-danger" type="submit" value="DELETE">
  <a href="{% url 'threads_detail' thread.id %}">Go back</a>
</form>

{% endblock %}

forums/templates/forums/thread_detail.html
{% extends 'base.html' %}
{% block title %}
{{ thread.title }}
{% endblock %}
{% block content %}

{% load bootstrap4 %}

<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url 'forums_home' %}">Forums</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{% url 'forums_detail' thread.forum.id %}">{{ thread.forum.title }}</a>
    </li>
    <li class="breadcrumb-item active">
      {{ thread.title }}
    </li>
  </ol>
</nav>

<small>created by <b>{{ thread.author.username }}</b> on {{ thread.created }}</small>
<h1>{{ thread.title }}</h1>
<a class="" href="{% url 'posts_create' thread.id %}">New Reply</a>
{% if user.is_authenticated and thread.author == user %}
<a class="text-danger float-right" href="{% url 'threads_delete' thread.id %}">Delete Thread</a>
{% endif %}

<hr>


{% for post in thread.post_set.all %}
<div>
  <div class="card mb-2">
    <div class="card-header">
      <a name="post{{ post.position }}">#{{ post.position }}</a>:
      <b>{{ post.author.username }}</b>
      {% if post.reply_to %}
      in reply to <a class="badge badge-pill badge-primary" 
                     href="#post{{ post.reply_to.position }}">#{{ post.reply_to.position }}</a>
      {% endif %}
      posted on {{ post.created }}

      {% if user.is_authenticated and post.author == user %}
      <div class="float-right">
        <a class="badge badge-secondary" href="{% url 'posts_edit' post.id %}">edit</a>
        <a class="badge badge-warning" href="{% url 'posts_delete' post.id %}">delete</a>
      </div>
      {% else %}
      <div class="float-right">
        <a class="badge badge-primary" href="{% url 'posts_reply' thread.id post.id %}">reply</a>
      </div>
      {% endif %}
    </div>
    <div class="card-body">
      {{ post.text }}
    </div>
  </div>
</div>
{% empty %}
Nothing here...
{% endfor %}

<h5 class="mt-3">Quick Post:</h5>
<form action="{% url 'posts_create' thread.id %}" method="post">
  {% csrf_token %}
  {% bootstrap_field post_form.text show_label=False %}
  <input class="btn btn-primary float-right" type="submit" value="Post">
</form>

{% endblock %}

forums/templates/forums/thread_form.html
{% extends 'base.html' %}
{% block title %}
New Thread
{% endblock %}
{% block content %}

{% load bootstrap4 %}

<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url 'forums_home' %}">Forums</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{% url 'forums_detail' forum.id %}">{{ forum.title }}</a>
    </li>
    <li class="breadcrumb-item active">
      New Thread
    </li>
  </ol>
</nav>

<h1>New Thread</h1>

<form action="" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button class="btn btn-primary" type="submit">Create Thread</button>
</form>

{% endblock %}