walkr/urls.py
import os

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views
from django.conf import settings

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('walks/', include('walks.urls')),
    path('forums/', include('forums.urls')),
]

if os.getenv('DEV'):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

walks/urls.py
from django.urls import path
#add something here
from . import views

urlpatterns = [
    path('', views.WalksList.as_view(), name='walks_home'),
    path('create_walk/', views.WalkCreate.as_view(), name="create_walk"),
    path('<int:walk_id>/add_stop/', views.StopCreate.as_view(), name="create_stop"),
    path('<int:walk_id>/stop/<int:stop_id>/add_photo/', views.PictureCreate.as_view(), name="create_picture"),
    path('<int:walk_id>/stop/<int:stop_id>/delete/<int:picture_id>/', views.PictureDelete.as_view(), name='delete_picture'),
    path('view_walk/<int:pk>/', views.WalkDetail.as_view(), name = 'walk_detail'),
    path('view_walk/<int:pk>/edit/', views.WalkEdit.as_view(), name = 'walk_edit'),
    path('view_walk/<int:pk>/delete/', views.WalkDelete.as_view(), name = 'walk_delete'),
    path('<int:walk_id>/stop/<int:stop_id>/', views.StopDetail.as_view(), name='stop_detail'),
    path('<int:walk_id>/stop/<int:stop_id>/edit/', views.StopEdit.as_view(), name='edit_stop'),
    path('<int:walk_id>/stop/<int:stop_id>/delete/', views.StopDelete.as_view(), name='delete_stop'),
]

walks/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

from forums.models import Thread, get_comments_forum
import uuid

User = get_user_model()


def make_unique_picture_filename(instance, filename):
    return uuid.uuid4().hex[:6] + filename[filename.rfind('.'):]


class Walk(models.Model):
    '''A full guided tour.'''
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=64)
    description = models.TextField(blank=True)
    is_public = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    comment_thread = models.OneToOneField(Thread, null=True, on_delete=models.SET_NULL)

    def save(self, *args, **kwargs):
        if self._state.adding:
            comment_thread = Thread.objects.create(
                title=f"Walk: {self.title}",
                forum=get_comments_forum(),
                author=self.user,
            )
            comment_thread.save()
            self.comment_thread = comment_thread

        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.title}: {self.description[:25]}"

    def get_absolute_url(self):
        return reverse ('walk_detail', args=[str(self.id)])


class Stop(models.Model):
    '''A location that is part of a Walk.'''
    walk = models.ForeignKey(Walk, on_delete=models.CASCADE)
    title = models.CharField(max_length=64)
    description = models.TextField(blank=True)
    location_text = models.CharField(max_length=256)
    order = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return f"{self.title} ({self.location_text}): {self.description[:25]}"

    def get_absolute_url(self):
        return reverse ('walk_detail', args=[str(self.walk.id)])


class Picture(models.Model):
    '''An illustration of a Stop.'''
    stop = models.ForeignKey(Stop, on_delete=models.CASCADE)
    title = models.CharField(max_length=64)
    image = models.ImageField(upload_to=make_unique_picture_filename)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse ('stop_detail', args=[str(self.stop.walk.id), str(self.stop.id)])

walks/views.py
from typing import DefaultDict
from .models import Walk, Stop, Picture
from django.views.generic.list import ListView
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin


class WalkCreate(LoginRequiredMixin, CreateView):
    template_name="walk_form.html"
    model = Walk
    fields = ['title', 'description', 'is_public']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class WalkDetail(DetailView):
    # breakpoint()
    model = Walk
    template_name = 'walk_detail.html'

    def get_object(self):
        obj = super().get_object()
        # Record the last accessed date
        obj.last_accessed = timezone.now()
        obj.save()
        return obj


class WalkEdit(LoginRequiredMixin, UpdateView):
    model = Walk
    template_name = 'walk_update_form.html'
    fields = ['title','description', 'is_public']

    def get_object(self):
        obj = Walk.objects.get(id=self.kwargs['pk'])
        return obj


class WalkDelete(LoginRequiredMixin, DeleteView):
    model = Walk
    template_name = 'walk_confirm_delete.html'

    def get_object(self):
        obj = Walk.objects.get(id=self.kwargs['pk'])
        return obj

    def get_success_url(self):
        return reverse('walks_home')


class WalksList(ListView):
    model = Walk
    template_name = 'walk_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class PictureCreate(LoginRequiredMixin, CreateView):
    model = Picture
    template_name = 'add_picture.html'
    fields = ['title', 'image']

    def get_context_data(self, **kwargs):
        obj = Stop.objects.get(id=self.kwargs['stop_id'])
        context = super().get_context_data(**kwargs)
        context['stop_title'] = obj.title
        context['walk_title'] = obj.walk.title
        context['stop_id'] = self.kwargs['stop_id']
        context['walk_id'] = self.kwargs['walk_id']
        return context

    def form_valid(self, form):
        form.instance.stop = Stop.objects.get(id=self.kwargs['stop_id'])
        return super().form_valid(form)



class PictureDelete(LoginRequiredMixin, DeleteView):
    model = Picture
    template_name = 'picture_confirm_delete.html'

    def get_object(self):
        obj = Picture.objects.get(id=self.kwargs['picture_id'])
        return obj

    def get_success_url(self):
        return reverse('stop_detail', kwargs={ 'walk_id': self.kwargs['walk_id'], 'stop_id': self.kwargs['stop_id'] })


class StopCreate(LoginRequiredMixin, CreateView):
    model = Stop
    template_name = "stop_form.html"
    fields = ['title','description', 'location_text', 'order']

    def get_context_data(self, **kwargs):
        obj = Walk.objects.get(id=self.kwargs['walk_id'])
        context = super().get_context_data(**kwargs)
        context['walk_title'] = obj.title
        context['walk_id'] = self.kwargs['walk_id']
        return context

    def form_valid(self, form):
        form.instance.walk = Walk.objects.get(id=self.kwargs['walk_id'])
        return super().form_valid(form)


class StopDetail(DetailView):
    model = Stop
    template_name = 'stop_detail.html'

    def get_object(self):
        obj = Stop.objects.get(id=self.kwargs['stop_id'])
        obj.stopsInWalk = Stop.objects.filter(walk_id=self.kwargs['walk_id']).order_by('created')
        obj.stopsInWalk.length = obj.stopsInWalk.count()
        key_no = 1
        dictionary_of_stops = {}
        for stop in obj.stopsInWalk:
            dictionary_of_stops[key_no] = stop
            if stop.id == self.kwargs['stop_id']:
                obj.currentStopNo=key_no
            key_no+=1
        #if the current stop is the first stop, set walk id and stop id of previous stop to -1
        if obj.currentStopNo == 1:
            obj.previous_stop_ID = -1
            obj.previous_walk_ID = -1
        else:
            obj.previous_stop_ID = dictionary_of_stops[obj.currentStopNo-1].id
            obj.previous_walk_ID = dictionary_of_stops[obj.currentStopNo-1].walk.id
        #if the current stop is the last stop, set walk id and stop id of next stop to -1
        if obj.currentStopNo == obj.stopsInWalk.length:
            obj.next_stop_ID = -1
            obj.next_walk_ID = -1
        else:
            obj.next_stop_ID = dictionary_of_stops[obj.currentStopNo+1].id
            obj.next_walk_ID = dictionary_of_stops[obj.currentStopNo+1].walk.id
        
        obj.last_accessed = timezone.now()
        obj.save()
        return obj


class StopEdit(LoginRequiredMixin, UpdateView):
    model = Stop
    template_name = 'stop_update_form.html'
    fields = ['title','description', 'location_text', 'order']

    def get_object(self):
        obj = Stop.objects.get(id=self.kwargs['stop_id'])
        return obj


class StopDelete(LoginRequiredMixin, DeleteView):
    model = Stop
    template_name = 'stop_confirm_delete.html'

    def get_object(self):
        obj = Stop.objects.get(id=self.kwargs['stop_id'])
        return obj

    def get_success_url(self):
        return reverse('walk_detail', kwargs={ 'pk': self.kwargs['walk_id'] })

walks/templates/add_picture.html
{% extends 'base.html' %}
{% block title %}
Add Picture
{% endblock %}
{% block content %}
{% load bootstrap4 %}

<div>
  <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'walk_detail' walk_id%}">{{walk_title}}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'stop_detail' walk_id stop_id%}">{{stop_title}}</a></li>
        <li class="breadcrumb-item active">
          Add Picture
        </li>
      </ol>
    </nav>
</div>

<h1>Add Picture</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-primary" type="submit" value="Upload Image">
</form>
{% endblock %}

walks/templates/picture_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
Delete Stop
{% endblock %}
{% block content %}

{% load bootstrap4 %}

<div>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'walk_detail' picture.stop.walk.id %}">{{picture.stop.walk.title}}</a></li>
          <li class="breadcrumb-item"><a href="{% url 'stop_detail' picture.stop.walk.id picture.stop.id %}">{{picture.stop.title}}</a></li>
          <li class="breadcrumb-item active">
            Delete Picture
          </li>
        </ol>
      </nav>
</div>


<h1>Delete Stop</h1>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete:</p>
    <img class="d-block img-thumbnail" src="{{picture.image.url}}">
    <input type="submit" value="Confirm">
</form>

{% endblock %}

walks/templates/stop_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
Delete Stop
{% endblock %}
{% block content %}

{% load bootstrap4 %}

<div>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'walk_detail' stop.walk.id%}">{{stop.walk.title}}</a></li>
          <li class="breadcrumb-item"><a href="{% url 'stop_detail' stop.walk.id stop.id%}">{{stop.title}}</a></li>
          <li class="breadcrumb-item active">
            Delete {{ stop.title }} in {{stop.walk.title}}
          </li>
        </ol>
      </nav>
</div>

<h1>Delete Stop</h1>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete " {{ stop.title }}"?</p>
    <input type="submit" value="Confirm">
</form>

{% endblock %}

walks/templates/stop_detail.html
{% extends 'base.html' %}
{% block title %}
Stop {{ stop.title }}
{% endblock %}
{% block content %}

{% load bootstrap4 %}
<div>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'walk_detail' stop.walk.id%}">{{stop.walk.title}}</a></li>
          <li class="breadcrumb-item active">{{stop.title}}</li>
        </ol>
      </nav>
</div>

  
<div class="p-4 mb-4">
    <div class="row">
    {% if stop.previous_stop_ID == -1 %}
    <a href="#" class="btn btn-primary disabled col-4">Previous Stop</a>
    {% else %}
    <a href="{% url 'stop_detail' stop.previous_walk_ID stop.previous_stop_ID %}" class="btn btn-primary col-4">Previous Stop</a>
    {% endif %}
    <div class="text-dark text-center col-4">STOP {{stop.currentStopNo}}/{{stop.stopsInWalk.length}}</div>
    {% if stop.next_stop_ID == -1 %}
    <a href="#" class="btn btn-primary disabled col-4">Next Stop</a>
    {% else %}
    <a href="{% url 'stop_detail' stop.next_walk_ID stop.next_stop_ID %}" class="col-4 btn btn-primary ">Next Stop</a>
    {% endif %}
    </div>
    </div>
  
{% if stop.picture_set.all %}
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
       <div class="carousel-inner">
       {% for picture in stop.picture_set.all %}
       {% with picture_set_size=stop.picture_set.count %}
       {% if picture_set_size == 1 %} 
       <div class="carousel-item row text-center active">
          <img class="d-block h-55 center img-fluid mx-auto" src="{{picture.image.url}}" alt="{{picture.title}}">
          <div class="d-block">
          {% if stop.walk.user == user or user.is_staff == True%}
            <a href ="{% url 'delete_picture' picture.stop.walk.id picture.stop.id picture.id %}" class="btn btn-sm btn-danger d-block delete-button">X</a>
            {% endif %}
        </div>
          <div class="carousel-caption d-block">
              <h5 class="image-caption">{{picture.title}}</h5>
          </div>
       </div>

       {% elif forloop.first %}
       <div class="carousel-item active">
             <img class="d-block h-55 img-fluid mx-auto" src="{{picture.image.url}}" alt="{{picture.title}}">
             <div class="d-block">
             {% if stop.walk.user == user or user.is_staff == True%}
               <a href ="{% url 'delete_picture' picture.stop.walk.id picture.stop.id picture.id %}" class="btn btn-sm btn-danger delete-button">X</a>
               {% endif %}
           </div>
             <div class="carousel-caption d-block">
                 <h5 class="image-caption">{{picture.title}}</h5>
             </div>
      </div>
      {% elif forloop.last %}
      <div class="carousel-item">
            <img class="d-block h-55 img-fluid mx-auto" src="{{picture.image.url}}" alt="{{picture.title}}">
            <div class="d-block">
            {% if stop.walk.user == user or user.is_staff == True%}
              <a href ="{% url 'delete_picture' picture.stop.walk.id picture.stop.id picture.id %}" class="btn btn-sm btn-danger delete-button">X</a>
              {% endif %}
          </div>
            <div class="carousel-caption d-block">
                <h5 class="image-caption">{{picture.title}}</h5>
            </div>
     </div>
       {% else %}
       <div class="carousel-item">
          <img class="d-block h-55 center img-fluid mx-auto" src="{{picture.image.url}}" alt="{{picture.title}}">
          <div class="d-block">
          {% if stop.walk.user == user or user.is_staff == True%}
            <a href ="{% url 'delete_picture' picture.stop.walk.id picture.stop.id picture.id %}" class="btn btn-sm btn-danger delete-button">X</a>
            {% endif %}
        </div>
          <div class="carousel-caption d-block">
              <h5 class="image-caption">{{picture.title}}</h5>
          </div>
       </div>
       {% endif %}
       {% endwith %}
       {% empty %}
       <div class="card mb-3">
             <div class="card-body">
               <h5 class="image-caption" class="card-title">No Pictures</h5>
               {% if stop.walk.user == user or user.is_staff == True%}
               <a href ="{% url 'delete_picture' picture.stop.walk.id picture.stop.id picture.id %}" class="btn btn-warning">Delete</a>
               {% endif %}
               <p class="card-text">There are currently no pictures for this walk, click "Add Picture" to get started!</p>
             </div>
           </div>
       {% endfor %}
   </div>
   <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
       <span class="carousel-control-prev-icon" aria-hidden="true"></span>
       <span class="sr-only">Previous</span>
   </a>
   <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
       <span class="carousel-control-next-icon" aria-hidden="true"></span>
       <span class="sr-only">Next</span>
  </a>
</div>
{% endif %}
{% if stop.walk.user == user or user.is_staff == True or stop.walk.is_public == True%}
<div class="mt-3 pb-4">
  {% if stop.walk.user == user or user.is_staff == True %}
  <a class = "btn btn-warning float-right mx-1" href="{% url 'delete_stop' stop.walk.id stop.id %}">Delete</a>
  <a class = "btn btn-secondary float-right mx-1" href="{% url 'edit_stop' stop.walk.id stop.id %}">Edit</a>
  {% endif %}
  {% if stop.walk.is_public == True %}
  <a class = "btn btn-primary float-right mx-1" href="{% url 'create_picture' stop.walk.id stop.id %}">Add Picture</a>
  {% endif %}
</div>
{% else %}
<p> Not able to add pictures </p>
{% endif %}



{% endblock %}

walks/templates/stop_form.html
{% extends 'base.html' %}
{% block title %}
Create Stop
{% endblock %}
{% block content %}

{% load bootstrap4 %}
<div>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'walk_detail' walk_id%}">{{walk_title}}</a></li>
          <li class="breadcrumb-item active">
            Add Stop
          </li>
        </ol>
      </nav>
</div>
<h1>New Stop</h1>
<form method="post">{% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-primary" type="submit" value="Create Stop">
</form>

{% endblock %}

walks/templates/stop_update_form.html
{% extends 'base.html' %}
{% block title %}
Edit Stop
{% endblock %}
{% block content %}

{% load bootstrap4 %}
<div>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'walk_detail' stop.walk.id%}">{{stop.walk.title}}</a></li>
          <li class="breadcrumb-item"><a href="{% url 'stop_detail' stop.walk.id stop.id%}">{{stop.title}}</a></li>
          <li class="breadcrumb-item active">
            Update {{ stop.title }} in {{stop.walk.title}}
          </li>
        </ol>
      </nav>
</div>

<h1>Change Stop Details</h1>
<form method="post">{% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-primary" type="submit" value="Update Stop">
</form>

{% endblock %}

walks/templates/walk_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
Delete Walk
{% endblock %}
{% block content %}

{% load bootstrap4 %}

<div>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'walk_detail' walk.id%}">{{walk.title}}</a></li>
          <li class="breadcrumb-item active">
            Delete {{walk.title}}
          </li>
        </ol>
      </nav>
</div>

<h1>Delete Walk</h1>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete " {{ walk.title }}"?</p>
    <input type="submit" value="Confirm">
</form>

{% endblock %}

walks/templates/walk_detail.html
{% extends 'base.html' %}
{% block title %}
{{walk.title}}
{% endblock %}
{% block content %}
    
<h1 class="title-caption">{{walk.title|upper}}</h1>
<div class="shadow text-dark bg-light text-center2 mt-4">
        <h4 class="d-inline">
            {% if walk.user == user or user.is_staff == True %}
            <div class="float-right">
                <a class="badge badge-secondary" href="{% url 'walk_edit' walk.id %}">EDIT</a>
                <a class="badge badge-warning" href="{% url 'walk_delete' walk.id %}">DELETE</a>
            </div>
            {% endif %}</h4>
        <h2>{{walk.description}}</h2>
        {% if walk.is_public == True %}
            {% if walk.description == "" %}
                 <p class="text-right pt-5"> Public Walk by {{walk.user}}</p>
            {% else %}
                <p class="text-right p-3"> Public Walk by {{walk.user}}</p>
            {% endif %}
    {% else %}
        {% if walk.description == "" %}
            <p class="text-right pt-5"> Private Walk by {{walk.user}}</p>
        {% else %}
            <p class="text-right p-3"> Private Walk by {{walk.user}}</p>
        {% endif %}
    {% endif %}
</div>
<div class="shadow-sm">

    {% for stop in walk.stop_set.all %}
    <a style="opacity:0.9"class="list-group-item" href= "{% url 'stop_detail' stop.walk.id stop.id%}">
        {{ stop.title }}<br> 
        <small>{{ stop.description }}</small>
        {% if walk.user == user or user.is_staff == True %}
        <a style="z-index: 11; top :-4.5vh" class="badge rounded-pill list-group-item d-inline bg-warning badge-warning float-right text-center mr-3" href="{% url 'delete_stop' stop.walk.id stop.id %}">DELETE</a>
        <a style="z-index: 11; top: -4.5vh" class="badge rounded-pill list-group-item d-inline bg-dark badge-secondary float-right text-center mr-3" href="{% url 'edit_stop' stop.walk.id stop.id%}">EDIT</a>
        {% endif %}
    </a>
    {% endfor %}
</div>
    
    <div class="flex-row justify-content-between mt-3">
        {% if walk.comment_thread %}
        <a class="btn btn-info p-2" href="{% url 'threads_detail' walk.comment_thread.id %}">View Comments...</a>
        {% endif %}
        
        {% if user == walk.user or user.is_staff == True or walk.is_public == True%}
        <a href='/walks/{{walk.id}}/add_stop/'  class="btn btn-primary p-2">Create Stop</a>
        {% endif %}
    </div>
    {% endblock %}
    

walks/templates/walk_form.html
{% extends 'base.html' %}
{% block title %}
New Walk
{% endblock %}
{% block content %}

{% load bootstrap4 %}

<h1>New Walk</h1>
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input class="btn btn-primary" type="submit" value="Create Walk">
</form>
{% endblock %}

walks/templates/walk_list.html
{% extends 'base.html' %}
{% block title %}
Walks
{% endblock %}
{% block content %}
<h1 class="title-caption">Walks</h1>
{% for walk in object_list %}
<div >
    {% if walk.is_public == False %} 
        {% if walk.user == user or user.is_staff == True %}
        <a style="opacity:0.9"class="list-group-item" href= "{% url 'walk_detail' walk.id %}">
            {{ walk.title }}<br> <small>
                {{ walk.description }}
            </small>
        {% endif %}
    {% else %}
    <a style="opacity:0.9"class="list-group-item" href= "{% url 'walk_detail' walk.id %}">
        {{ walk.title }}<br> <small>
            {{ walk.description }}
        </small>
    {% endif %}
        {% if walk.user == user or user.is_staff == True %}
        <a style="z-index: 11; top :-4.5vh" class="badge rounded-pill list-group-item d-inline bg-warning badge-warning float-right text-center mr-3" href="{% url 'walk_delete' walk.id %}">DELETE</a>
        <a style="z-index: 11; top: -4.5vh" class="badge rounded-pill list-group-item d-inline bg-dark badge-secondary float-right text-center mr-3" href="{% url 'walk_edit' walk.id %}">EDIT</a>
        {% endif %}
    </a>
</div>
    {% empty %}
    <li>No Walks Yet!</li>
    {% endfor %}
    <a href="{% url 'create_walk' %}" class="btn btn-primary mt-3">Create Walk</a>
    {% endblock %}

walks/templates/walk_update_form.html
{% extends 'base.html' %}
{% block title %}
Edit Walk
{% endblock %}
{% block content %}

{% load bootstrap4 %}
<div>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'walk_detail' walk.id%}">{{walk.title}}</a></li>
          <li class="breadcrumb-item active">
            Edit {{walk.title}}
          </li>
        </ol>
      </nav>
</div>

<h1>Change Walk Details</h1>
<form method="post">{% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-primary" type="submit" value="Update Walk">
</form>

{% endblock %}